services:
  app:
    build: .
    container_name: file-analysis-app
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload